substitutions:
  _IMAGE_NAME: 'ghcr.io/tvaroska/teval'
  _IMAGE_TAG: 'latest'
  _TOX_ENV: ''  # Empty = run all, or specify like 'py312-pydanticlatest'

steps:
  # Run tests directly in /workspace (Cloud Build will pull the image automatically)
  # The /workspace directory contains the cloned repository code
  - name: '${_IMAGE_NAME}:${_IMAGE_TAG}'
    env:
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
    entrypoint: 'bash'
    timeout: '1200s'  # 20 min timeout for tests
    args:
      - '-c'
      - |
        set -euo pipefail
        cd /workspace

        # Run tox in parallel mode or specific environment
        if [ -z "${_TOX_ENV}" ]; then
          echo "Running full tox matrix in parallel..."
          tox -p auto
        else
          echo "Running specific environment: ${_TOX_ENV}"
          tox -e ${_TOX_ENV}
        fi

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # 8 vCPUs for parallel tox execution
  timeout: '1800s'  # 30 min global timeout
